#include "opencv2/objdetect.hpp"
#include "opencv2/video/tracking.hpp"
#include "opencv2/highgui.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/videoio.hpp"
#include "opencv2/core/matx.hpp"
#include <iostream>
#include <fstream>
#include <chrono>
#include <vector>
#include <future>
#include <deque>
#include <math.h>
#include <stdlib.h>
#include <stdio.h>
#include "fftw3.h"
#include "Python.h"
#include "matplotlibcpp.h"
